export const EmployeetableColumns = [
    {
      label: "Employee",
      prop: "name",
      width: 150,
      fixed: true,
    },
    {
      label: "Email",
      prop: "email",
      width: 250,
      fixed: false,
    },
    {
      label: "Position",
      prop: "position",
      width: 200,
      fixed: false,
    },
    {
      label: "Salary",
      prop: "salary",
      width: 150,
      fixed: false,
    },
    {
      label: "Role",
      prop: "role",
      width: 150,
      fixed: false,
    },
    {
      label: "Password",
      prop: "password",
      width: 150,
      fixed: false,
    },
    {
      label: "Department",
      prop: "department",
      width: 150,
      fixed: false,
    },
    {
      label: "Date of Birth",
      prop: "date_of_birth",
      width: 150,
      fixed: false,
    },
    {
      label: "NRC",
      prop: "nrc",
      width: 150,
      fixed: false,
    },
    {
      label: "Address",
      prop: "address",
      width: 200,
      fixed: false,
    },
    {
      label: "Phone",
      prop: "phone",
      width: 150,
      fixed: false,
    },
    {
      label: "Gender",
      prop: "gender",
      width: 100,
      fixed: false,
    },
    {
      label: "Skills",
      prop: "skills",
      width: 200,
      fixed: false,
      show_overflow_tooltip: true,
    },
    // {
    //   label: "Emergency Contact",
    //   prop: "emergency_contact",
    //   width: 150,
    //   fixed: false,
    // },
    // {
    //   label: "Emergency Contact Number",
    //   prop: "emergency_contact_number",
    //   width: 150,
    //   fixed: false,
    // },
    {
      label: "Joining Date",
      prop: "joining_date",
      width: 150,
      fixed: false,
    },
    {
      label: "System Status",
      prop: "system_status",
      width: 150,
      fixed: false,
    },
  ];
  
  export const EmployeetableData = [
    {
      name: "John Doe",
      email: "john.doe@example.com",
      position: "Software Engineer",
      salary: "1500 USD",
      role: "Developer",
      password: "********",
      department: "IT",
      date_of_birth: "1990-01-15",
      nrc: "12/ABC(N)123456",
      address: "123 Main St, Yangon",
      phone: "+959123456789",
      gender: "Male",
      skills: "JavaScript, React, Node.js",
      emergency_contact: "Jane Doe",
      emergency_contact_number: "+959987654321",
      joining_date: "2020-05-01",
      system_status: "Active",
    },
    {
      name: "Alice Brown",
      email: "alice.brown@example.com",
      position: "Project Manager",
      salary: "2000 USD",
      role: "Manager",
      password: "********",
      department: "Operations",
      date_of_birth: "1985-03-10",
      nrc: "14/DEF(N)654321",
      address: "456 Market St, Mandalay",
      phone: "+959234567890",
      gender: "Female",
      skills: "Leadership, Agile, Scrum",
      emergency_contact: "Bob Brown",
      emergency_contact_number: "+959876543210",
      joining_date: "2019-03-15",
      system_status: "Active",
    },
    {
      name: "Charlie Smith",
      email: "charlie.smith@example.com",
      position: "Designer",
      salary: "1200 USD",
      role: "Designer",
      password: "********",
      department: "Creative",
      date_of_birth: "1992-07-22",
      nrc: "11/GHI(N)789012",
      address: "789 Elm St, Naypyidaw",
      phone: "+959345678901",
      gender: "Male",
      skills: "UI/UX, Figma, Adobe XD",
      emergency_contact: "Eve Smith",
      emergency_contact_number: "+959765432109",
      joining_date: "2021-09-10",
      system_status: "Active",
    },
    {
      name: "David Wilson",
      email: "david.wilson@example.com",
      position: "Marketing Specialist",
      salary: "1300 USD",
      role: "Marketer",
      password: "********",
      department: "Marketing",
      date_of_birth: "1988-12-05",
      nrc: "13/JKL(N)234567",
      address: "321 Maple Ave, Bago",
      phone: "+959456789012",
      gender: "Male",
      skills: "SEO, Content Marketing, Google Ads",
      emergency_contact: "Fiona Wilson",
      emergency_contact_number: "+959654321098",
      joining_date: "2018-11-20",
      system_status: "Inactive",
    },
    {
      name: "Emily Johnson",
      email: "emily.johnson@example.com",
      position: "HR Manager",
      salary: "1800 USD",
      role: "Manager",
      password: "********",
      department: "Human Resources",
      date_of_birth: "1995-04-17",
      nrc: "15/MNO(N)345678",
      address: "654 Pine Rd, Taunggyi",
      phone: "+959567890123",
      gender: "Female",
      skills: "Recruitment, Employee Relations, Payroll",
      emergency_contact: "George Johnson",
      emergency_contact_number: "+959543210987",
      joining_date: "2017-02-05",
      system_status: "Active",
    },
  ];